baseURL = "https://test-hugo-site.netlify.com/"
languageCode = "en-us"
title = "Test Hugo Site"
theme = "coder"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[outputs]
  home = ["HTML", "RSS", "JSON"] # Adds JSON to default outputs for search functionality

[params]
    author = "Zac Heisey"
    description = "Testing Ground for Hugo SSG"
    keywords = "hugo,website,static"
    info = "Test Hugo Site"

    hideCredits = false
    hideCopyright = false

    # Custom CSS
    custom_css = []

    # RTL support
    rtl = false

[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/zac-heisey"
[[params.social]]
    name = "Twitter"
    weight = 2
    url = "https://twitter.com/zac_heisey/"
[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/zacheisey/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/blog/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
[[menu.main]]
    name = "Store"
    weight = 3
    url = "/store/"    
[[menu.main]]
    name = "Search"
    weight = 4
    url = "/search/"
