---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: heading
  label: Data Files
- type: directory
  path: data
  label: Products
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.1
